### ISSUE TITLE
Column positions must be scalar

### ISSUE THREAD

**Issue by Clarkhsiung** [thierrygosselin/grur#11]
I tried to used missing_visualization to get summary of genomic data.
However, I can not produce the plot & table, such as heatmap, missing summary table, manhattan and violin plots.

Here is my code.
`library(grur)
missing_visualization(data ="populations.snps.vcf",
                      strata = "popmap.tsv",
                      parallel.core = 1)`

And here is my error message

Analysing percentage missing ...
Error: Column positions must be scalar
Call `rlang::last_error()` to see a backtrace

Computation time, overall: 24 sec
############################ missing_visualization #############################
> rlang::last_error()
`<error>
message: Column positions must be scalar
class:   `rlang_error`
backtrace:
  1. grur::missing_visualization(...)
  5. purrr::map(...)
  6. grur:::.f(.x[[i]], ...)
  7. [ `%<>%`(...) ] with 7 more calls
 16. dplyr:::rename.data.frame(., STRATA_SELECT = data[[!!(strata.select)]])
 17. tidyselect::vars_rename(names(.data), !!!enquos(...))
 18. tidyselect:::vars_rename_eval(quos, .vars)
 19. purrr::map2_chr(renamed, names(quos), validate_renamed_var, vars)
 20. tidyselect:::.f(.x[[1L]], .y[[1L]], ...)
 21. rlang::switch_type(...)
Call `rlang::last_trace()` to see the full backtrace`

How can I solve this problem?
Is there any dependent package need to install?

Attached is the file I used.

[population.zip](https://github.com/thierrygosselin/grur/files/3583953/population.zip)

**Comment by thierrygosselin** [comment]
Thanks for reporting 
I'll have a look at this today

**Comment by thierrygosselin** [comment]
I was able to reproduce the error, so it's a good thing!

**Comment by thierrygosselin** [comment]
With the new commit, your data should work
