### ISSUE TITLE
Error in dplyr::mutate()

### ISSUE THREAD

**Issue by DenisGoryunov** [thierrygosselin/grur#12]
Hi,
I got the error when ran the command `ibm <- grur::missing_visualization( data ="my_file.vcf")`:

"Error in `dplyr::mutate()`:
! Problem while computing `MISSING_PROP =
  round(...)`.
Caused by error in `.DynamicClusterCall()`:
! One of the nodes produced an error: Can not open file 'C:\Users\user\Documents\missing_visualization_20220222@2214\radiator_20220222@2214.gds'. The process cannot access the file because it is being used by another process.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
In SeqArray::seqVCF2GDS(vcf.fn = data, out.fn = filename, parallel = FALSE,  :
  Unknown INFO ID 'QualityScore' is ignored (it should be defined in the meta-information lines)."

when run `grur 0.1.4` package within `R studio` on the `Windows 10` laptop. How can i fix it?

In addition, may i ask you a few questions regarding package installation please?
I initially tried install it with commands (way 1):
```
install.packages("remotes")
remotes::install_github("thierrygosselin/grur")
```
After that a huge number of the packages was installed or updated, but i was not able to install the grur package eventually.
Then i tried it with commands (way 2):

```
if (!require("devtools")) install.packages("devtools")
install.packages("tidyverse")
install.packages("gsl")
devtools::install_github("thierrygosselin/grur")
devtools::[install_github](https://devtools.r-lib.org//reference/remote-reexports.html)("thierrygosselin/assigner")
```

Lots and lots of packages were installed or updated again and i was not able to install grur. Only after `Rtools` installation `grur` was successfully installed on my laptop.
Which way (way 1 or way 2 ) is correct?
Can my previously installed `R packages` and dependecies be broken during the `grur` installation?

Regards,
Denis

**Comment by thierrygosselin** [comment]
not helping Russians

**Comment by DenisGoryunov** [comment]
Thank you so much for your prompt reply!
