### ISSUE TITLE
grur::missing_visualization error

### ISSUE THREAD

**Issue by mcrossley3** [thierrygosselin/grur#16]
Hello, I created a filtered vcf using radiator::filter_rad(), and would like to examine missingness using grur::missing_visualization.

However, when I ran the following command:

ibm = grur::missing_visualization(data='./filter_rad_20230531@1305/13_filtered/radiator_data_20230531@1317.vcf', strata='strata_pb.txt')

I got the following error:

Error: 'generate_id_stats' is not an exported object from 'namespace:radiator'

Is there a simple fix that I am missing?

**Comment by mcrossley3** [comment]
I should have included the full output to the console prior to the error - here it is:

################################################################################
######################## grur::missing_visualization ###########################
################################################################################
Execution date/time: 20230531@1540

::grurmissing_visualization function call arguments:
    data = ./filter_rad_20230531@1305/13_filtered/radiator_data_20230531@1317.vcf
    strata = strata_pb.txt
    strata.select = POP_ID
    distance.method = euclidean
    ind.missing.geno.threshold = 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90
    filename = NULL
    parallel.core = 15
    write.plot = TRUE

Default "..." arguments assigned in ::grurmissing_visualization:
    path.folder = NULL


Folder created: missing_visualization_20230531@1540
File written: grur_missing_visualization_data_args_20230531@1540.tsv

Importing data
✔ Reading VCF [102ms]
                                                                                                         
Cleaning VCF
                                                                    
Filter monomorphic markers
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0
                                                                    
Filter common markers:
Number of individuals / strata / chrom / locus / SNP:
    Blacklisted: 0 / 0 / 0 / 0 / 0
                                                                    
VCF info:
Number of chromosome/contig/scaffold: 1
Number of locus: 1305
Number of markers: 1305
Number of strata: 10
Number of individuals: 127

Number of ind/strata:
Colony_21 = 5
Worth_19 = 10
Emanuel_19 = 10
Jefferson_19 = 6
Worth1_20 = 27
RandolphP_20 = 19
RandolphS_20 = 17
Worth2_20 = 21
Worth2_21 = 5
Worth1_21 = 7

Number of duplicate id: 0
radiator Genomic Data Structure (GDS) file: radiator_20230531@1540.gds
Error: 'generate_id_stats' is not an exported object from 'namespace:radiator'

Computation time, overall: 3 sec

**Comment by thierrygosselin** [comment]
That internal function is deprecated and no longer used, try uninstalling radiator and grur and reinstalling it.

Not that it matters but it was replaced by `generate_stats` that handle both individuals and markers stats.

Re-open the issue if you're still experiencing a problem.
