### ISSUE TITLE
Error running missing_visualization: Maximal number of DLLs reached...

### ISSUE THREAD

**Issue by ksil91** [thierrygosselin/grur#4]
I just install this package today (Ubuntu v16.04, R v3.4.1), and the install seemed to go successfully. When I ran this code:

`library(grur)
ibm <- missing_visualization(data = "../Inputs/OL-c85-t88-Breps-m50x68-maf025-u.vcf",strata = "../Making_Files/OL-c85-t88-Breps.pop")`

I received this message:
`Folder created:`   
`missing_visualization_20180313@1706`  
`Importing data`  
`VCF is biallelic`   
`Error in dyn.load(file, DLLpath = DLLpath, ...) : unable to load shared object '/home/ksilliman/R/x86_64-pc-linux-gnu-library/3.4/tidyselect/libs/tidyselect.so: maximal number of DLLs reached...`

Full traceback:
![screenshot from 2018-03-13 17-10-53](https://user-images.githubusercontent.com/8800355/37372672-98fae990-26e1-11e8-9739-14cbf80708ca.png)

Thanks!

**Comment by thierrygosselin** [comment]
Try starting a new R session without tons of loaded libraries. 
It's the only thing I can see. And only one other person running linux reported the problem before.
If it's still not working, send me the vcf and strata I'll check if there's a problem with it.

Best
Thierry

**Comment by ksil91** [comment]
Fixed it, thanks!
