### ISSUE TITLE
Error in eigen(delta1) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by Astahlke** [thierrygosselin/grur#5]
Hi Thierry, 

Any suggestions for troubleshooting this error? 

`> genlight`
 /// GENLIGHT OBJECT /////////

 // 51 genotypes,  13,936 binary SNPs, size: 1.9 Mb
 200845 (28.26 %) missing data

 // Basic content
   @gen: list of 51 SNPbin

 // Optional content
   @ind.names:  51 individual labels
   @loc.names:  13936 locus labels
   @chromosome: factor storing chromosomes of the SNPs
   @position: integer storing positions of the SNPs
   @pop: population of each individual (group size range: 1-17)
   @other: a list containing: elements without names

Proportion of missing genotypes (overall): 0.282587

`> missing_dat <- grur::missing_visualization(genlight)`
#######################################################################
#######################################################################
Folder created:
missing_visualization_20180412@1213

Importing data
Scanning for monomorphic markers...
    Number of markers before = 13936
    Number of monomorphic markers removed = 0

Tidy genomic data:
    Number of markers: 13936
    Number of chromosome/contig/scaffold: 1
    Number of individuals: 51
    Number of populations: 15

Informations:
Number of populations: 15
Number of individuals: 51
Number of ind/pop:
Arbon,_ID = 5
Ashton,_ID = 1
Conrad,_MT = 2
Denton,_MT = 2
Hermiston,_OR = 17
Kalispell,_MT = 1
Kimberly = 1
Kimberly,_ID = 3
McAmmon,_ID = 2
Neely,_ID = 2
Picabo,_ID = 4
Rexbug,_ID = 2
Ririe,_ID = 4
Soda_Springs,_ID = 3
Townsend,_MT = 2

Number of duplicate id: 0
Number of chrom/scaffolds: 1
Number of locus: 13936
Number of SNPs: 13936

Proportion of missing genotypes (overall): 0.282587

Identity-by-missingness (IBM) analysis using
    Principal Coordinate Analysis (PCoA)...
Generating Identity by missingness plot
Error in eigen(delta1) : infinite or missing values in 'x'

**Comment by thierrygosselin** [comment]
Hi Amanda, I think it's because some of you pop/strata contains only 1 sample. Try combining to have >= 2 and re-open the issue if you still get an error.

Will change to generate better error/warning
Thanks
Thierry
