### ISSUE TITLE
Missing_visualization: Error in UseMethod("ungroup") :    no applicable method 

### ISSUE THREAD

**Issue by pbpearman** [thierrygosselin/grur#8]
Hi Thierry,
I get the following error when running missing_visualization on the tutorial file "example_vcf2dadi_ferchaud_2015.vcf" and on a .vcf of my own:

$ ibm <- grur::missing_visualization(data = "example_vcf2dadi_ferchaud_2015.vcf", strata = "strata.stickleback.tsv")
Folder created: 
missing_visualization_20181209@1523

Importing data

Reading VCF...
Generated a filters parameters file: filters_parameters_20181209@1523.tsv

Number of SNPs: 31802
Number of samples: 177

conversion timing: 1 sec

VCF: biallelic SNPs
Cleaning VCF sample names

Synchronizing sample IDs in VCF and strata...
Reads assembly: reference-assisted
Filters parameters file: updated

Number of chromosome/contig/scaffold: 196
Number of locus: 17095
Number of markers: 31802
Number of individuals: 177

Working time: 1 sec

Deprecated function, update your code to use: filter_monomorphic

Scanning for monomorphic markers...
    Number of markers before/blacklisted/after: 31802/0/31802

Tidy genomic data:
    Number of markers: 31802
    Number of chromosome/contig/scaffold: 196
    Number of individuals: 177
    Number of populations: 8

Informations:
Number of populations: 8
Number of individuals: 177
Number of ind/pop:
HAD = 21
HAL = 19
KIB = 17
KRO = 20
MOS = 20
MAR = 20
NOR = 20
ODD = 40

Number of duplicate id: 0
Number of chrom/scaffolds: 196
Number of locus: 17095
Number of SNPs: 31802

Proportion of missing genotypes (overall): 0.022169

Identity-by-missingness (IBM) analysis using
    Principal Coordinate Analysis (PCoA)...
Generating Identity by missingness plot

Redundancy analysis...

Error in UseMethod("ungroup") : 
  no applicable method for 'ungroup' applied to an object of class "character"
In addition: Warning message:
Trying to compute distinct() for variables not found in the data:
- `strata.select`
This is an error, but only a warning is raised for compatibility reasons.
The operation will return the input unchanged. 
################################################
The ibm object is not generated. No blacklists or PCoA statistics are generated.  I am on Mac, with updated RStudio 1.1.383. The command was run from the RStudio console.  Can anyone replicate this behavior, or is it just my system??  Any suggestions?

> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray

**Comment by thierrygosselin** [comment]
Hi Peter, I'm working hard to release version 1 of radiator and will check your bugs after.
Thanks for reporting
Thierry

**Comment by thierrygosselin** [comment]
This should be fixed in the latest release
Thanks for reporting
